name: Rebase

on:
  schedule:
    - cron: '00 10 * * *'

jobs:
  build:
    name: Automatic rebase
    runs-on: ubuntu-20.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install git
    - name: Rebase
      run: |
        git config --global user.name "${GITHUB_USER}"
        git config --global user.email "${GITHUB_EMAIL}"
        git clone https://"${GITHUB_USER}":"${GITHUB_TOKEN}"@github.com/SirRGB/android_device_oneplus_msm8998-common.git -b lineage-20
        cd android_device_oneplus_msm8998-common
        git fetch https://github.com/LineageOS/android_device_oneplus_msm8998-common.git lineage-20
        git rebase FETCH_HEAD
        git push -f
      env:
        GITHUB_EMAIL: ${{ secrets.EMAIL }}
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        GITHUB_USER: ${{ secrets.USERNAME }}
